# Generated by Django 2.1.1 on 2018-10-11 00:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_colomn_details',
            fields=[
                ('index_num', models.IntegerField(primary_key=True, serialize=False, verbose_name='章节序号')),
                ('title', models.CharField(max_length=50, verbose_name='章节名称')),
                ('content', ckeditor.fields.RichTextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('read_num', models.IntegerField(default=0)),
                ('get_good', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Book')),
            ],
            options={
                'verbose_name_plural': '章节详情',
            },
        ),
    ]
